services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/Users

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
